name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write # Needed for commit to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Create .nojekyll file
        run: touch ./docs/.nojekyll

      - name: Build
        run: pnpm run build:safe
      
      - name: List build output for debugging
        run: ls -la docs/
        
      - name: Commit docs to repository
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add docs
          git commit -m "Update GitHub Pages deployment" || echo "No changes to commit"
          git push 