name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      # Install pnpm separately to use no-frozen-lockfile
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build site
        run: pnpm run build
        
      # Create custom static files (this will be placed in the dist directory, which is the build output)
      - name: Create fallback files
        run: |
          # Create a proper 404.html file
          cat > ./dist/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0;url=/puffy-phase/en/">
            <title>Page Not Found - Redirecting</title>
            <script>
              window.location.href = "/puffy-phase/en/";
            </script>
          </head>
          <body>
            <h1>Page Not Found</h1>
            <p>Redirecting to <a href="/puffy-phase/en/">English version</a>...</p>
          </body>
          </html>
          EOL
          
          # Fix the root index.html
          cat > ./dist/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0;url=/puffy-phase/en/">
            <title>Redirecting to English version</title>
            <script>
              window.location.href = "/puffy-phase/en/";
            </script>
          </head>
          <body>
            <p>Redirecting to <a href="/puffy-phase/en/">English version</a>...</p>
          </body>
          </html>
          EOL
          
          # Ensure .nojekyll file exists
          touch ./dist/.nojekyll
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 